name: Deploy to Production

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR Information
        id: pr_info
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Branch: ${{ github.head_ref }}"
          echo "PR Base Branch: ${{ github.base_ref }}"

      - name: Echo the PR Information
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Branch: ${{ github.head_ref }}"
          echo "PR Base Branch: ${{ github.base_ref }}"

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
