name: Check Who Approved

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: read
  contents: read
  id-token: write
  actions: write

jobs:
  check-approval:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Ensure the repository is checked out

      - name: Set up GitHub CLI
        run: sudo apt-get install -y gh

      - name: Get PR Number
        id: get_pr_number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr view ${{ github.event.pull_request.number }} --json number --jq '.number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Get PR Reviews
        id: get_pr_reviews
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APPROVAL_INFO=$(gh pr view ${{ env.PR_NUMBER }} --json reviews --jq '.reviews | map(select(.state == "APPROVED")) | .[-1]')
          REVIEWER_NAME=$(echo "$APPROVAL_INFO" | jq -r '.author.login')
          echo "REVIEWER_NAME=$REVIEWER_NAME" >> $GITHUB_ENV

      - name: Check Approver
        id: check_approver
        run: |
          if [ "${{ env.REVIEWER_NAME }}" != "ashiqpradeepsolutions" ]; then
            echo "Error: Deployment not approved by the specified approver."
            exit 1
          fi
